### ISSUE TITLE
BelongsTo whereHas with fully qualified columns

### ISSUE THREAD

**Issue by fntneves** [staudenmeir/eloquent-json-relations#30]
Hello,

Before anything else, thank you for this package.
It definitely should be included in Laravel's core.

I'm facing a limitation now regarding the BelongsTo relationship and whereHas.

Consider the `data` attribute of the Notification model.
In my use case, it contains a custom field — `activity_id` — that references another model. Therefore the following is achieved: Notification -- *BelongsTo* --> Activity.

Using `whereHas` from the BelongsTo relationship as follows is causing a PDOException:

```
$user->notifications()->whereHas('activity')->get();
```

The error is:

```
Caused by
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text ->> unknown
LINE 1: ...t * from "activities" where "notifications"."data"->>'activi...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

/home/vagrant/code/carsight/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Connection.php:335
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Connection.php:662
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Connection.php:629
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Connection.php:338
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2149
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2137
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2609
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2138
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2236
/home/vagrant/code/carsight/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2207
```

I suspect it is related to fully qualified columns.

I am using:
- v1.3.1 of this package.
- Laravel 6.18.8
- PostgreSQL 10.12

**Comment by staudenmeir** [comment]
Can you share the `Notification` and the `Activity` model?

**Comment by fntneves** [comment]
Sure:

Activity Model:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
    /**
     * The "type" of the primary key ID.
     *
     * @var string
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'published_at' => 'datetime',
    ];

    public function actor()
    {
        return $this->morphTo();
    }

    public function object()
    {
        return $this->morphTo();
    }
}
```

Notification Model:
```php
<?php

namespace App;

use Illuminate\Notifications\DatabaseNotification;

class Notification extends DatabaseNotification
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'data' => 'json',
        'read_at' => 'datetime',
    ];

    public function activity()
    {
        return $this->belongsTo(Activity::class, 'data->activity_id');
    }
}
```

Exception Stack Trace:
```
Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text ->> unknown
LINE 1: ...t * from "activities" where "notifications"."data"->>'activi...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

/home/vagrant/code/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:335
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:662
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:629
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:338
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2149
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2137
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2609
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2138
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2236
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2207
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:720
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:23
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php:385
/home/vagrant/code/app/app/Http/Controllers/GetNotificationsController.php:25
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:349
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/home/vagrant/code/app/app/Http/Controllers/GetNotificationsController.php:26
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php:59
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:683
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:624
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:613
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:170
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
/home/vagrant/code/app/vendor/fideloper/proxy/src/TrustProxies.php:57
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:63
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:145
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:468
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:440
/home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:270
/home/vagrant/code/app/tests/Feature/GetNotificationsTest.php:59
```

**Comment by staudenmeir** [comment]
What type of column is `activities.id`?

**Comment by fntneves** [comment]
It is of `uuid` type.

**Comment by staudenmeir** [comment]
I've released a new version that adds support for UUID keys.

You need to add the `HasJsonRelationships` trait and an `id` cast to the model:

```php
class Activity extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
        'id' => 'uuid',
        'published_at' => 'datetime',
    ];
}
```

**Comment by fntneves** [comment]
Still not working with the new release.

The generated query is the following:

```sql
select * from "notifications"
	where "notifications"."notifiable_id" = 1
		and "notifications"."notifiable_id" is not null
		and "notifications"."notifiable_type" = 'users'
		and exists (
			select * from "activities"
				where ("notifications"."data"->>'activity_id')::uuid = "activities"."id") 
	order by "created_at" desc
```

The error is in the `("notifications"."data"->>'activity_id')::uuid` part.

Adding the `json` keyword, like  `("notifications"."data"::json->>'activity_id')::uuid`, it works.

I already have the `json` cast for `data` attribute in `Notification` model.

**Comment by staudenmeir** [comment]
What's the whole error message?

**Comment by fntneves** [comment]
Running directly in `psql` command line, it is:

```
Query 1 ERROR: ERROR:  operator does not exist: text ->> unknown
LINE 7:     where ("notifications"."data"->>'activity_id')::uuid = "...
                                         ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by staudenmeir** [comment]
Can you share a database dump of both tables? I can't reproduce the issue.

**Comment by fntneves** [comment]
You can create the tables using the following SQL queries and you're good to go.
I've reproduced it in PostgreSQL 12 (in pgAdmin online).

```
CREATE TABLE "public"."activities" (
    "id" uuid NOT NULL,
    "actor_type" varchar(255) NOT NULL,
    "actor_id" int8 NOT NULL,
    "object_type" varchar(255),
    "object_id" int8,
    "published_at" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."notifications" (
    "id" uuid NOT NULL,
    "type" varchar(255) NOT NULL,
    "notifiable_type" varchar(255) NOT NULL,
    "notifiable_id" int8 NOT NULL,
    "data" text NOT NULL,
    "read_at" timestamp(0),
    "created_at" timestamp(0),
    "updated_at" timestamp(0),
    "activity_id" uuid,
    CONSTRAINT "notifications_activity_id_foreign" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE CASCADE,
    PRIMARY KEY ("id")
);
```

Not working query:
```
select * from "notifications"
	where "notifications"."notifiable_id" = 1
		and "notifications"."notifiable_id" is not null
		and "notifications"."notifiable_type" = 'users'
		and exists (
			select * from "activities"
				where ("notifications"."data"->>'activity_id')::uuid = "activities"."id") 
	order by "created_at" desc
```

Working query:
```
select * from "notifications"
	where "notifications"."notifiable_id" = 1
		and "notifications"."notifiable_id" is not null
		and "notifications"."notifiable_type" = 'users'
		and exists (
			select * from "activities"
				where ("notifications"."data"::json->>'activity_id')::uuid = "activities"."id") 
	order by "created_at" desc
```

**Comment by fntneves** [comment]
Question: Can the **text** column in `data` database field the root cause of this?

**Comment by fntneves** [comment]
Yep, that's it. The `text` column requires the `json` cast in SQL query.

It is working now...

Sorry for the inconvenient caused by this (non-)issue. At least the uuid types are now supported 😁 

Thank you for all your support!

**Comment by staudenmeir** [comment]
When you upgrade to Laravel 8, you need to adjust the cast:

```php
use Staudenmeir\EloquentJsonRelations\Casts\Uuid;

class Activity extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
        'id' => Uuid::class,
        'published_at' => 'datetime',
    ];
}
```
